# Configurations
title:            AdsRefine
longtitle:        AdsRefine - Mobile Advertising Resources Website
author:           Jane. R
email:            976368957@qq.com
description: >
  A mobile-focused website dedicated to advertising resources, providing AI ad generation methods, advertising concept quick reference, and other professional resources.

version:          1.0
gitbook_version:  3.2.3

url:              'https://www.adsrefine.com'
baseurl:          ""
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min:   1
  h_max:   3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  adsgen:
    output: true
    permalink: /:collection/:path/
    hidden_show: true
  concepts:
    output: true
    permalink: /:collection/:path/
    hidden_show: true
  contact:
    output: true
    permalink: /:collection/:path/
    hidden_show: true

ordered_collections:
  # - posts
  - adsgen
  - concepts
  - contact

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji

defaults:
  - scope:
      path: ""
    values:
      toc:
        enabled: true
        h_min: 1
        h_max: 3
      sidebar:
        template: toc-date
